### ISSUE TITLE
Path spaces not properly escaped in geth init script

### ISSUE THREAD

**Issue by brampurnot** [ConsenSys/quorum-wizard#109]
Hey,

I'm trying to run this on my local macBook with macOS Catalina but I'm getting the following exception when initializing Quorum: 
(node:5046) UnhandledPromiseRejectionWarning: Error: Command failed: cd /Users/******/Documents/**Visual Studio.nosync**/quorum7nodes/wizard-new/network/3-nodes-quickstart && /Users/i306392/.quorum-wizard/bin/quorum/2.7.0/geth --datadir qdata/dd1 init qdata/dd1/genesis.json 2>&1
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at executeSync (/usr/local/lib/node_modules/quorum-wizard/src/utils/execUtils.js:5:10)
    at forEach (/usr/local/lib/node_modules/quorum-wizard/src/generators/bashHelper.js:26:37)
    at Array.forEach (<anonymous>)
    at initBash (/usr/local/lib/node_modules/quorum-wizard/src/generators/bashHelper.js:26:16)
    at createDirectory (/usr/local/lib/node_modules/quorum-wizard/src/index.js:75:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

The problem is related to the folder in the path highlighted in bold. Instead of Visual Studio.nosync" it should be "Visual\ Studio.nosync" on a mac.

Bram

**Comment by bmcd** [comment]
Good catch! We'll put a fix in for this asap.

By the way, that path is going to be too long to run quorum anyway, because of a limit of 108 characters. We will have a warning for this (issue #105) in the next release as well. So try running from a folder that's not so deeply nested and not inside a folder with a space for now.

Thanks!

**Comment by brampurnot** [comment]
Thanks for the info! Was able to run it from a different folder.
