### ISSUE TITLE
Some generated files are owned by root user, even when running as an unprivileged user.

### ISSUE THREAD

**Issue by benjamincburns** [ConsenSys/quorum-wizard#112]
I assume when generating keys, the current user's UID isn't passed to docker, resulting in some config files being written under root ownership. See the following console log for details. Running with `sudo` seems to be a workaround, but I don't feel too great about the potential security implications of mixing `npx` and `sudo`.

```
(LAPTOP-9H6AG8MK) 2020-10-15T16:15:59 😁  
λ npx quorum-wizard
npx: installed 183 in 7.772s
?
Welcome to Quorum Wizard!

This tool allows you to easily create bash, docker, and kubernetes files to start up a quorum network.
You can control consensus, privacy, network details and more for a customized setup.
Additionally you can choose to deploy our chain explorer, Cakeshop, to easily view and monitor your network.

We have 3 options to help you start exploring Quorum:

  1.  Quickstart - our 1 click option to create a 3 node raft network with tessera and cakeshop

  2.  Simple Network - using pregenerated keys from quorum 7nodes example,
      this option allows you to choose the number of nodes (7 max), consensus mechanism, transaction manager, and the option to deploy cakeshop

  3.  Custom Network - In addition to the options available in #2, this selection allows for further customization of your network.
      Choose to generate keys, customize ports for both bash and docker, or change the network id

Quorum Wizard will generate your startup files and everything required to bring up your network.
All you need to do is go to the specified location and run start.sh

 Custom Network
? Would you like to generate bash scripts, a docker-compose file, or a kubernetes config to bring up your network? docker-compose
? Select your consensus mode - istanbul is a pbft inspired algorithm with transaction finality while raft provides faster blocktimes, transaction finality and on-demand block creation istanbul
? Input the number of nodes (2-7) you would like in your network - a minimum of 4 is recommended 2
? Which version of Quorum would you like to use? Quorum 2.7.0
? Choose a version of tessera if you would like to use private transactions in your network, otherwise choose "none" Tessera 0.10.5
? What tools would you like to deploy alongside your network? (Press space to select options, then press enter) Cakeshop, Quorum's official block explorer
? Would you like to generate keys for your network? (selecting 'no' will use insecure keys that are not suitable for Production use) Yes
? 10 is the default network id in quorum but you can use a different one 10
? What would you like to call this network? 2-nodes-istanbul-tessera-docker-compose
? Would you like to customize your node ports? No
Building network directory...
Pulling docker container and generating network resources...
rm: cannot remove 'nodes.yaml': No such file or directory
(node:997) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/home/bburns/network/2-nodes-istanbul-tessera-docker-compose/out/config/permissioned-nodes.json'
    at Object.openSync (fs.js:474:3)
    at writeFileSync (fs.js:1436:35)
    at writeFile (/home/bburns/.npm/_npx/997/lib/node_modules/quorum-wizard/src/utils/fileUtils.js:40:3)
    at generateResourcesRemote (/home/bburns/.npm/_npx/997/lib/node_modules/quorum-wizard/src/generators/networkCreator.js:70:5)
    at createDirectory (/home/bburns/.npm/_npx/997/lib/node_modules/quorum-wizard/src/index.js:77:5)
    at buildNetwork (/home/bburns/.npm/_npx/997/lib/node_modules/quorum-wizard/src/index.js:65:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


(LAPTOP-9H6AG8MK) 2020-10-15T16:36:33 😁   ~
λ ls network/2-nodes-istanbul-tessera-docker-compose/out/config/ -al
total 44
drwxr-xr-x 4 root root 4096 Oct 15 16:33 .
drwxr-xr-x 3 root root 4096 Oct 15 16:33 ..
-rw-r--r-- 1 root root 1158 Oct 15 16:33 genesis.json
-rw-r--r-- 1 root root  126 Oct 15 16:33 istanbul-validator-config.toml
drwxr-xr-x 2 root root 4096 Oct 15 16:33 key1
drwxr-xr-x 2 root root 4096 Oct 15 16:33 key2
-rw-r--r-- 1 root root  312 Oct 15 16:33 nodes.yaml
-rw-r--r-- 1 root root  407 Oct 15 16:33 permissioned-nodes.json
-rw-r--r-- 1 root root 1932 Oct 15 16:33 tessera-config-9.0.json
-rw-r--r-- 1 root root 1974 Oct 15 16:33 tessera-config-enhanced.json
-rw-r--r-- 1 root root 1678 Oct 15 16:33 tessera-config.json

```

**Comment by bmcd** [comment]
Yeah we definitely don't want people running the wizard with sudo. Security issues aside, it causes problems when you later try to start the network due to permission issues with the various resources.

I'm guessing the root problem here is that the files that are generated by the container in the resource generation step have the owner set to whatever user is running the docker service itself. So if you're running docker desktop on mac/windows, there probably isn't an issue. If docker is running under another user, then we get this issue.

I'm going to look into it further and see what the best solution is. Thanks!

**Comment by libby** [comment]
@benjamincburns what OS were you running on, and how did you install docker?

**Comment by benjamincburns** [comment]
I'm running Ubuntu on WSL2 under Windows. I'm running Docker Desktop installed with the WSL2 backend, so the docker socket that I get in the WSL environment is actually a proxy back over to Docker Desktop.

I'd be surprised if this didn't repro in other more vanilla setups, though. By default, unless you pass a UID to docker, the UID used inside of the container is 1. This means that if files are written out to a mounted directory, they'll get root ownership by default.

**Comment by bmcd** [comment]
Should be fixed in the next release. Can you try `npx quorum-wizard@next` to use the beta version and see if it solves the problem? I tested on ubuntu in a vm and also using WSL2.

The solution was to pass in the uid and gid, then run `chown` on the output files/folders inside the container. Luckily chown doesn't care if those users/groups exist in the container, so it lets us do this.
